language: go

os:
  - linux
  - osx

go:
  - 1.16.x
  - 1.15.x
  - 1.14.x
  - 1.13.x
  - tip

before_script:
  - go get -u -v github.com/mattn/goveralls
  - go get -t -v ./...

script:
  - go test -v -cover -race ./... -coverprofile=.coverprofile

  # send coverage
  - $HOME/gopath/bin/goveralls -coverprofile=.coverprofile -service=travis-ci

jobs:
  allow_failures:
    - go: tip

  include:
    - stage: cross compilation
      script:
        - GOOS=linux go build -o /dev/null ./cmd/...
        - GOOS=darwin go build -o /dev/null ./cmd/...
        - GOOS=freebsd go build -o /dev/null ./cmd/...
        - GOOS=windows go build -o /dev/null ./cmd/...
        - GOARCH=386 go build -o /dev/null ./cmd/...
